<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <EnableHardwareControlGuard>true</EnableHardwareControlGuard>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\TrackPlanPage.axaml.cs">
      <DependentUpon>TrackPlanPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controlls\InterlockingEnlements\SingalTiles\SignalTileMemory.axaml.cs">
      <DependentUpon>SignalTileMemory.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controlls\InterlockingEnlements\SingalTiles\SignalTileNoMemory.axaml.cs">
      <DependentUpon>SignalTileNoMemory.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controlls\InterlockingEnlements\TrackTiles\TrackTiles.axaml.cs">
      <DependentUpon>TrackTiles.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controlls\InterlockingEnlements\ButtonTiles\ControllButtonTiles.axaml.cs">
      <DependentUpon>ControllButtonTiles.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controlls\InterlockingEnlements\ButtonTiles\AutomaticButtonTiles.axaml.cs">
      <DependentUpon>AutomaticButtonTiles.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="WsrTestWindow.axaml.cs">
      <DependentUpon>WsrTestWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="RelayPlanWindow.axaml.cs">
      <DependentUpon>RelayPlanWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="BlockTestWindow.axaml.cs">
      <DependentUpon>BlockTestWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Remove="Stations\bahnhof-1\Routes.xml" />
  </ItemGroup>
</Project>
